./alpine-make-vm-image \
--arch riscv64 \
--image-format qcow2 \
--image-size 250M \
--repositories-file example/repositories \
--packages "$(cat example/packages)"  \
--fs-skel-dir example/rootfs \
--fs-skel-chown root:root \
--serial-console \
-k lts \
--script-chroot alpine-riscv64-$(date +%Y-%m-%d).qcow2 \
-- ./example/configure.sh
